### PR TITLE
MLOOKAT and DWRITEFMT fixed

### LINKED ISSUE #34: Some GPU Instructions are failing
Seems to have begun after #27, and isn't fixed by #28 

Error that shows up
```
[wire-cpu] ZVM:[0:48: ')' expected (to close '(' at line 47) near 'local'
  1. Precompile_Finalize - addons/wire-cpu/lua/wire/zvm/zvm_core.lua:361
   2. Step - addons/wire-cpu/lua/wire/zvm/zvm_core.lua:642
    3. Run - addons/wire-cpu/lua/entities/gmod_wire_gpu/cl_init.lua:159
     4. RenderGPU - addons/wire-cpu/lua/entities/gmod_wire_gpu/cl_init.lua:249
      5. unknown - addons/wire-cpu/lua/entities/gmod_wire_gpu/cl_init.lua:354

[ZVM ERROR]: unknown error
```

For 3D examples, the code is being finalized while it's half finished (trailing "variable +" something from what I could tell by printing the entire emitblock on error)

For other examples(like the trig one), instructions using % for modulo or trying to check if a character is "%" have errors due to string.format attempting to parse them as a replacement.

Needs further investigation.

### PR DESCRIPTION
**Pull request by DerelictDrone**
Should fix #34 

MLOOKAT was missing a ) for its first three dyn_emits (this fixes all the 3d examples)

DWRITEFMT needed to have its % string checks replaced with %%%% to get them through the string.formats on Dyn_Emit and Emit, and a % operator use replaced with math.mod

### CODE REVIEW

File: lua/wire/zvm/zvm_opcodes.lua [hunk 1]
```diff
@@ -1576,9 +1576,9 @@ end
 ZVM.OpcodeTable[267] = function(self)   --MLOOKAT
   local seg1code = self.EmitOperandSegment[1] and "0" or "VM.DS"
   local seg2code = self.EmitOperandSegment[2] and "0" or "VM.DS"
-  self:Dyn_Emit("$L EYE    = VM:ReadVector3f($2 + %s+0",seg2code)
-  self:Dyn_Emit("$L CENTER = VM:ReadVector3f($2 + %s+3",seg2code)
-  self:Dyn_Emit("$L UP     = VM:ReadVector3f($2 + %s+6",seg2code)
+  self:Dyn_Emit("$L EYE = VM:ReadVector3f($2 + VM."..(self.EmitOperandSegment[2] or "DS").."+0)")
```
Comment (thegrb93) [inline lua/wire/zvm/zvm_opcodes.lua:1579]: These can still use %s right?

Comment (DerelictDrone) [reply lua/wire/zvm/zvm_opcodes.lua]: Actually yeah, that was how I fixed it initially(just adding the right parenthesis), I think I copy & pasted the original lines to test if the behavior was the same and forgot to put the fixed ones that use seg2code back

**Review by thegrb93 — APPROVED** [review]
