### PR TITLE
Emit & Dyn_emit now wrap string.format + Vector instruction segment fix

### LINKED ISSUE #26: Instructions that handle segment:pointer adds segment to address twice
So far, I've discovered that this affects every vector instruction in zvm_opcodes

When just using segment:register outside of a memory access, it will be treated as segment+register, 
gmod_nQmP1U5IjK

However, the vector instructions, which are supposed to accept segment:register, expect them to not be added by default, so they add the segment value to the register value.

These functions should only check if segment exists, otherwise apply DS as segment.
```
ZVM.OpcodeTable[250] = function(self)  --VADD
  self:Dyn_Emit("if VM.VMODE == 2 then")
    self:Dyn_Emit("$L V1 = VM:ReadVector2f($1 + VM."..(self.EmitOperandSegment[1] or "DS")..")")
    self:Dyn_Emit("$L V2 = VM:ReadVector2f($2 + VM."..(self.EmitOperandSegment[2] or "DS")..")")
    self:Dyn_EmitInterruptCheck()
    self:Dyn_Emit("VM:WriteVector2f($1 + VM."..(self.EmitOperandSegment[1] or "DS")..",")
      self:Dyn_Emit("{x = V1.x+V2.x, y=V1.y+V2.y, z=0})")
    self:Dyn_EmitInterruptCheck()
  self:Dyn_Emit("elseif VM.VMODE == 3 then")
    self:Dyn_Emit("$L V1 = VM:ReadVector3f($1 + VM."..(self.EmitOperandSegment[1] or "DS")..")")
    self:Dyn_Emit("$L V2 = VM:ReadVector3f($2 + VM."..(self.EmitOperandSegment[2] or "DS")..")")
    self:Dyn_EmitInterruptCheck()
    self:Dyn_Emit("VM:WriteVector3f($1 + VM."..(self.EmitOperandSegment[1] or "DS")..",")
      self:Dyn_Emit("{x = V1.x+V2.x, y=V1.y+V2.y, z=V1.z+V2.z})")
    self:Dyn_EmitInterruptCheck()
  self:Dyn_Emit("end")
end
```

The LEA instruction is unaffected because it returns 0 if the right operand is not a memory expression (I.E not [SEG:REG] or SEG:#REG)

### PR DESCRIPTION
**Pull request by DerelictDrone**
May fix #26 for vector instructions, tested with VADD but needs further testing on the other VEXP instructions.

Implements @Vurv78's suggestion for ZVM:Emit() and ZVM:Dyn_Emit(), since they take strings, making them wrap string.format() to stop concatenating strings and numbers in a potentially unsafe manner.

Converts all known calls to dyn_emit and emit that concatenate numbers in zvm_opcodes and gmod_wire_cpu to use %d

Dyn_EmitOperand remains unaffected at the moment due to taking multiple args already

### CODE REVIEW

File: lua/wire/zvm/zvm_opcodes.lua [hunk 1]
```diff
@@ -1231,128 +1231,181 @@ end
 
 --------------------------------------------------------------------------------
 ZVM.OpcodeTable[250] = function(self)  --VADD
+  local seg1code,seg2code = "0","0"
+  if not self.EmitOperandSegment[1] then
+    seg1code = "VM.DS"
+  end
+  if not self.EmitOperandSegment[2] then
+    seg2code = "VM.DS"
+  end
```
Comment (thegrb93) [inline lua/wire/zvm/zvm_opcodes.lua:1240]: Shouldn't seg1code and seg2code be `self.EmitOperandSegment[1]` and `self.EmitOperandSegment[2]` if they are set?

Comment (thegrb93) [reply lua/wire/zvm/zvm_opcodes.lua:1240]: EmitOperandSegment needs to be checked for validity if that's the case otherwise it still poses a threat.

**Comment by thegrb93** [comment]
Looks like an improvement, but is a huge cost to performance as well. I'd like to see the 'Emit' shit replaced with actual lua rather than string-building into compiled lua code

File: lua/wire/zvm/zvm_opcodes.lua (hunk 1 above)
Comment (DerelictDrone) [reply lua/wire/zvm/zvm_opcodes.lua:1240]: This is for fixing #26, which is that if they have a segment set it would add the segment to it twice, because if say, FS = 6 and R0 = 2, passing FS:R0 to these instructions is the same as passing 8, but these instructions expect it to just be the value of R0 rather than the value of FS + R0, so it would end up trying to load a vector from memory index 14(6+8) rather than index 8(6+2)

The only time this isn't the case is when a segment isn't used, where it instead defaults to adding VM.DS, because the value of the operand isn't getting segment added to it by default, so I default it to adding 0 if there's a segment in that spot to avoid adding it twice without breaking the functionality of non-memory uses of segment:reg offsetting, because reading variables in functions use this trick(they do RSTACK REG,EBP:const a lot for 3 byte access that doesn't modify the ptr register)

[the remark this answers is not in the document]
Comment (DerelictDrone) [reply lua/wire/zvm/zvm_opcodes.lua:1240]: It seems like that works, so sure, I'll get a commit for it in a moment.

**Comment by DerelictDrone** [comment]
> Looks like an improvement, but is a huge cost to performance as well. I'd like to see the 'Emit' shit replaced with actual lua rather than string-building into compiled lua code at some point. This is fine for now at least.

I have been wondering if there may be a performance improvement in reducing the number of calls to string format and global emit/dyn_emit, by possibly replacing them with a version that builds a smaller, local string(saving the arguments), then calling the global emit at the end which will run string.format once on the whole instruction's code rather than string.formatting and concatenating to the entire block on every emit/dyn_emit

I'd like to ask others that are more familiar with lua's performance regarding the local part, but I imagine less frequent (but bigger) calls to string.format would go a long way

**Comment by thegrb93** [comment]
Yeah the less concats and formats, the better.

**Comment by thegrb93** [comment]
You could potentially combine a bunch of those groups of emits into a single emit.

**Review by thegrb93 — APPROVED** [review]

**Comment by Vurv78** [comment]
> Looks like an improvement, but is a huge cost to performance as well. I'd like to see the 'Emit' shit replaced with actual lua rather than string-building into compiled lua code at some point. This is fine for now at least.

Didn't realize it ran at runtime. That is pretty terrible. Then again the emit function itself is very laggy just looking at the code. It uses string concatenation so a `string.format` call is the least of our problems considering the huge amount of allocations this alone is causing.

If it were me I'd refactor it to store it properly as a string buffer and only table.concat when it's needed, and replace the varargs with parameters a-f.

**Review by Vurv78 — CHANGES_REQUESTED** [review]
Should change this emit function too, no?
https://github.com/wiremod/wire-cpu/blob/39b3a4b7e4af5a61e3a9b43662e0bb54fd602329/lua/wire/zvm/zvm_core.lua#L28

**Comment by DerelictDrone** [comment]
> Should change this emit function too, no?
> 
> https://github.com/wiremod/wire-cpu/blob/39b3a4b7e4af5a61e3a9b43662e0bb54fd602329/lua/wire/zvm/zvm_core.lua#L28

@Vurv78 That one can only occur if microcodedebug is on, the only condition that sets it is if not SERVER and not CLIENT, I don't know if such a state is possible outside of running it outside of gmod, or manually assigning it

**Comment by DerelictDrone** [comment]
> > Looks like an improvement, but is a huge cost to performance as well. I'd like to see the 'Emit' shit replaced with actual lua rather than string-building into compiled lua code at some point. This is fine for now at least.
> 
> Didn't realize it ran at runtime. That is pretty terrible. Then again the emit function itself is very laggy just looking at the code. It uses repeated string concatenation so a `string.format` call is the least of our problems considering the huge amount of allocations this alone is causing.
> 
> If it were me I'd refactor it to store it properly as a string buffer and only `table.concat` when it's needed, and replace the varargs with parameters a-f so the code can jit compile.

I'm fairly certain these will only run on compile/precompile, I.E that section is only encountered for the first time and hasn't been modified by the CPU itself

I've noticed that you can tell easily when something like the GPU is starting a precompile by it flashing the "took too long to draw frame!" the first time you enter a new block.

**Comment by Vurv78** [comment]
> > Should change this emit function too, no?
> > https://github.com/wiremod/wire-cpu/blob/39b3a4b7e4af5a61e3a9b43662e0bb54fd602329/lua/wire/zvm/zvm_core.lua#L28
> 
> @Vurv78 That one can only occur if microcodedebug is on, the only condition that sets it is if not SERVER and not CLIENT, I don't know if such a state is possible unless you're running it outside of gmod, or manually assigning it

Then if it's unused you could remove it or add a comment saying so and leave it for later

**Comment by Vurv78** [comment]
> > > Looks like an improvement, but is a huge cost to performance as well. I'd like to see the 'Emit' shit replaced with actual lua rather than string-building into compiled lua code at some point. This is fine for now at least.
> > 
> > 
> > Didn't realize it ran at runtime. That is pretty terrible. Then again the emit function itself is very laggy just looking at the code. It uses repeated string concatenation so a `string.format` call is the least of our problems considering the huge amount of allocations this alone is causing.
> 
> I'm fairly certain these will only run on compile/precompile, I.E that section is only encountered for the first time and hasn't been modified by the CPU itself
> 
> I've noticed that you can tell easily when something like the GPU is starting a precompile by it flashing the "took too long to draw frame!" the first time you enter a new block.
> 
> > If it were me I'd refactor it to store it properly as a string buffer and only `table.concat` when it's needed, and replace the varargs with parameters a-f so the code can jit compile.
> 
> If you think this'll help I can do it.

If it's not runtime then it doesn't really matter, so up to you. I just skimmed over the code because @thegrb93 said it'd be a perf hit. I did initially think it only ran to compile once

**Comment by DerelictDrone** [comment]
I should probably test to check if the emits are run every time, or if they only build a precompiled block, I'm fairly certain it's only while building a precompiled block but it would also be good to see how frequently blocks get precompiled to see how big a hit to performance this may result in.

**Comment by DerelictDrone** [comment]
I've got some basic tests to measure the amount of time spent in the precompile functions on two separate branches, one before these changes, and one after these changes

Before:
image

After:
image

Confirm for yourselves using these two branches
[perf-testing](https://github.com/DerelictDrone/wire-cpu/tree/perf-testing) (before)
[perf-test-post-emit](https://github.com/DerelictDrone/wire-cpu/tree/perf-test-post-emit) (after)

**Comment by thegrb93** [comment]
I wasn't concerned with a huge latency increase, just knew it would be slightly more expensive. I imagine most of the latency is from reallocations.

**Comment by thegrb93** [comment]
I think vurv just wants a comment added to that emit function and this can be merged.

**Comment by DerelictDrone** [comment]
Marked them all w/ a comment
